#!/usr/bin/env python3
"""
Render the nginx vhost from the template.

Two XHTTP path modes are supported:

1) Dedicated path (e.g. /xhttp or /api/v3)
   -> that location proxies to Xray, everything else serves the website.

2) Root path (client config has path "/" or "/?ed=2048")
   -> the path cannot be used to split traffic, so requests are split by SHAPE:
        - any URI starting with a session UUID (/<uuid> or /<uuid>/<seq>) -> Xray
        - any POST request                                               -> Xray
        - everything else (browser/crawler GET on /)                     -> website
   XHTTP clients always append the session UUID to the path and send uplink
   data as POST, so existing client configs keep working unchanged while
   browsers and crawlers see a normal website.

The website locations are written once to site_common.inc and included by both
the plain-HTTP server and the TLS server. Cloudflare terminates TLS in front of
us, so the HTTP server serves the real site instead of redirecting to https.
"""
import sys, os

tpl_path, out_path, local_tls, xport, xpath, primary, maxmb = sys.argv[1:8]
http_ports = sys.argv[8] if len(sys.argv) > 8 else "80"
enable_tls = (sys.argv[9] if len(sys.argv) > 9 else "1") == "1"

listen_lines = []
for i, p in enumerate([x.strip() for x in http_ports.split(",") if x.strip()]):
    d = " default_server" if i == 0 else ""
    listen_lines.append(f"    listen {p}{d};")
    listen_lines.append(f"    listen [::]:{p}{d};")
HTTP_LISTEN = "\n".join(listen_lines)

PROXY = """        proxy_pass http://xhttp_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        access_log off;"""

UUID = r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"

clean = (xpath or "").strip().strip("/")
root_mode = (clean == "")

if root_mode:
    xhttp_loc = (
        "    # ===== VPN traffic (XHTTP on root path) =====\n"
        "    # requests beginning with a session UUID -> Xray\n"
        f'    location ~ "^/{UUID}(/.*)?$" {{\n{PROXY}\n    }}'
    )
    root_loc = (
        "    # XHTTP uplink is always POST; browsers and crawlers use GET.\n"
        "    location / {\n"
        "        if ($request_method = POST) {\n"
        "            proxy_pass http://xhttp_backend;\n"
        "        }\n"
        "        try_files $uri $uri/ /index.php?$query_string;\n"
        "    }"
    )
else:
    xhttp_loc = (
        "    # ===== VPN traffic (XHTTP) - must come before the website =====\n"
        f"    location /{clean} {{\n{PROXY}\n    }}"
    )
    root_loc = "    location / { try_files $uri $uri/ /index.php?$query_string; }"

COMMON = f"""# generated by render_vhost.py - shared website locations
add_header X-Content-Type-Options nosniff always;
add_header Referrer-Policy strict-origin-when-cross-origin always;

location = /robots.txt   {{ try_files /robots.txt =404; }}
location = /sitemap.xml  {{ try_files /sitemap.xml =404; }}

location /f/ {{ alias /var/www/data/uploads/; internal; }}

location ~ \\.php$ {{
    fastcgi_pass php_backend;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /var/www/site$fastcgi_script_name;
    fastcgi_read_timeout 300s;
    client_max_body_size {maxmb}m;
}}

location ~* \\.(css|js|svg|png|ico|woff2)$ {{
    expires 7d;
    add_header Cache-Control "public, max-age=604800";
}}

location ~ "^/d/([A-Za-z0-9]{{6,32}})$" {{
    rewrite "^/d/([A-Za-z0-9]{{6,32}})$" /d.php?id=$1 last;
}}

{root_loc}

error_page 404 /404.php;
location = /404.php {{
    fastcgi_pass php_backend;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /var/www/site/404.php;
}}
"""

inc_path = os.path.join(os.path.dirname(out_path), "site_common.inc")
open(inc_path, "w", encoding="utf-8").write(COMMON)

s = open(tpl_path, encoding="utf-8").read()
if not enable_tls:
    marker = "# ---------- TLS terminated site"
    if marker in s:
        s = s[:s.index(marker)]

s = (s.replace("__XHTTP_LOC__", xhttp_loc)
       .replace("__HTTP_LISTEN__", HTTP_LISTEN)
       .replace("__LOCAL_TLS_PORT__", local_tls)
       .replace("__XHTTP_PORT__", xport)
       .replace("__PRIMARY__", primary)
       .replace("__MAX_UPLOAD_MB__", maxmb))
open(out_path, "w", encoding="utf-8").write(s)
print("[render] mode=" + ("root-path" if root_mode else "/" + clean)
      + "  http ports=" + http_ports
      + "  tls-layer=" + ("on" if enable_tls else "OFF"))
